#!/usr/bin/env python3
"""PreToolUse: the write rules, enforced before the write happens.

Reads the hook payload on stdin and answers `deny`, `ask` or `allow` — `allow`
silently. These are the gate's rules moved earlier, where a violation costs a
sentence rather than a turn. The repo is found through `CLAUDE_PROJECT_DIR`;
with none set there is nothing to police and this stays silent.
"""
import json
import os
import sys

# Refusals only. The warnings at 500 lines and 30 lines of a CLAUDE.md are the
# gate's, because a hook's `ask` overrides every permission mode by design.
# `xtask/src/rules.rs` carries the same numbers; the two must not drift.
FAIL_LINES = 900
CLAUDE_MD_FAIL = 50
COMMENT_BLOCK_CAP = 15

# Where bytes enter the process, plus the gate that names the pattern it bans.
JSON_ALLOWED = ("crates/store/", "crates/ipc/", "xtask/")


def answer(decision: str, reason: str) -> None:
    """Emit a PreToolUse decision and exit. `allow` is silent by convention."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": decision,
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    root = os.environ.get("CLAUDE_PROJECT_DIR")
    if not root:
        sys.exit(0)

    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not path:
        sys.exit(0)

    try:
        rel = os.path.relpath(path, root).replace("\\", "/")
    except ValueError:
        sys.exit(0)
    if rel.startswith(".."):
        sys.exit(0)  # outside the repo: not this gate's business

    # A worktree is a checkout of its own: every rule below judges a path by
    # the checkout it is in, not by the session's root.
    checkout, rel = in_checkout(root, rel)

    # ---- rule: nothing is written into a checkout that is on `main` ------
    #
    # No gate can catch this — the wrong checkout leaves no trace in a diff. 35
    # files landed on `main` in one session, from a `cd` that did not persist.
    if on_main(checkout):
        answer(
            "deny",
            f"{rel} is in the checkout at `main`, which is never edited. Cut a "
            "worktree and write there instead:\n"
            f"  git -C {checkout} worktree add {checkout}/.claude/worktrees/<name> -b <branch>\n"
            "Then give every path you write the worktree's own prefix. A `cd` "
            "does not survive to the next tool call — the call after it runs "
            "from the main checkout again, which is how a relative path ends up "
            "here.",
        )

    # ---- rule: a generated file is not hand-edited -----------------------
    #
    # The gate fails on a hand-edited output only after it is committed, by
    # which time the turn is spent. There is no list here: every generator
    # writes the same marker, so the hook asks the file rather than a list.
    if os.path.exists(path):
        try:
            with open(path, encoding="utf-8", errors="ignore") as f:
                head = f.read(400)
        except OSError:
            head = ""
        if "GENERATED by `cargo xtask" in head:
            task = head.split("GENERATED by `", 1)[1].split("`", 1)[0]
            answer(
                "deny",
                f"{rel} is generated. Editing it here is thrown away by the next "
                f"run and fails the gate in between. Change what it is generated "
                f"from, then run `{task}`.",
            )
            return

    # ---- rule: no serde_json::from_* outside store and ipc ---------------
    #
    # Rust source only, matching the gate rule exactly. Wider once, and it
    # refused a contract describing the ban that the gate would have passed.
    written = tool_input.get("content") or tool_input.get("new_string") or ""
    rust_source = rel.endswith(".rs") and rel.split("/", 1)[0] in (
        "crates", "apps", "packages", "xtask",
    )
    if rust_source and "serde_json::from_" in written and not rel.startswith(JSON_ALLOWED):
        answer("deny", f"{rel} would contain `serde_json::from_*`. Untyped JSON "
                       "belongs to `store` and `ipc`, the two places bytes enter "
                       "the process; everywhere else a value arrives typed.")

    # ---- rule: a comment block runs to fifteen lines and no further ------
    # Same cap as the gate, refused rather than warned: new writes should not
    # add to a backlog the gate merely reports. Judges the fragment being
    # written, not the file it lands in.
    source_scope = rel.endswith((".rs", ".ts", ".tsx")) and rel.split("/", 1)[0] in (
        "crates", "apps", "packages", "xtask",
    )
    if source_scope and written:
        worst = worst_comment_run(written)
        if worst > COMMENT_BLOCK_CAP:
            answer("deny", f"{rel} would add a comment block of {worst} lines, over "
                           f"{COMMENT_BLOCK_CAP}. A comment is a line or two; reduce "
                           "it or file it. `.claude/skills/comments/SKILL.md`")

    # ---- rule: a CLAUDE.md routes, it does not explain -------------------
    lines = projected_lines(root, rel, tool_input)
    if rel.endswith("CLAUDE.md") and lines is not None:
        if lines > CLAUDE_MD_FAIL:
            answer("deny", f"{rel} would be about {lines} lines, over "
                           f"{CLAUDE_MD_FAIL}. A CLAUDE.md routes; it does not "
                           "explain. Move the explanation to a practice doc, a "
                           "skill or Notion and leave the pointer. v1's agent "
                           "file reached 328 lines one reasonable paragraph at "
                           "a time.")

    # ---- rule: 900 lines of source fails ---------------------------------
    #
    # Source only, matching `no_file_too_long`. A hook stricter than the gate
    # produces workarounds, not fixes — the scopes are part of the rule.
    if lines is not None and rel.endswith((".rs", ".ts", ".tsx")) and rel.split("/", 1)[0] in (
        "crates", "apps", "packages", "xtask",
    ):
        if lines > FAIL_LINES:
            answer("deny", f"{rel} would be about {lines} lines, over {FAIL_LINES}. "
                           "Split it.")

    sys.exit(0)


def in_checkout(root: str, rel: str) -> "tuple[str, str]":
    """The checkout a repo-relative path is in, and the path within that checkout.

    A worktree under `.claude/worktrees/` or `.armada/worktrees/` is its own.
    """
    for prefix in (".claude/worktrees/", ".armada/worktrees/"):
        if rel.startswith(prefix):
            name, _, within = rel[len(prefix):].partition("/")
            if within:
                return os.path.join(root, prefix, name), within
    return root, rel


def on_main(root: str) -> bool:
    """Whether the checkout at `root` has `main` checked out.

    Read from `.git` to keep a subprocess off every write. Unreadable answers
    `False`: a hook that cannot tell where it is must not refuse a write.
    """
    git = os.path.join(root, ".git")
    if os.path.isfile(git):
        try:
            with open(git, encoding="utf-8") as f:
                pointer = f.read().strip()
        except OSError:
            return False
        if not pointer.startswith("gitdir:"):
            return False
        git = pointer.split(":", 1)[1].strip()
    try:
        with open(os.path.join(git, "HEAD"), encoding="utf-8") as f:
            return f.read().strip() == "ref: refs/heads/main"
    except OSError:
        return False


def worst_comment_run(text: str) -> int:
    """Longest run of consecutive comment lines in `text`. Same detection as
    `rules.rs`'s `no_comment_block_too_long`: a line starting `//`, `*` or
    `/*`. A blank or code line ends the run."""
    run = worst = 0
    for line in text.splitlines():
        t = line.strip()
        if t.startswith("//") or t.startswith("*") or t.startswith("/*"):
            run += 1
            worst = max(worst, run)
        else:
            run = 0
    return worst


def projected_lines(root: str, rel: str, tool_input: dict) -> "int | None":
    """Line count the file would have after this write.

    Exact for `Write`; estimated for `Edit` from the delta between the strings,
    since the hook runs before the edit and only ever compares to a threshold.
    """
    content = tool_input.get("content")
    if content is not None:
        return len(content.splitlines())

    old, new = tool_input.get("old_string"), tool_input.get("new_string")
    if old is None or new is None:
        return None
    try:
        with open(os.path.join(root, rel)) as f:
            current = len(f.read().splitlines())
    except OSError:
        return None
    delta = len(new.splitlines()) - len(old.splitlines())
    if tool_input.get("replace_all"):
        return None  # occurrence count is unknown before the edit runs
    return current + delta


main()
