#!/usr/bin/env python3
"""PreToolUse: the three write rules, enforced before the write happens.

Reads the hook payload on stdin and answers with a permission decision:

  deny  — the write must not happen
  ask   — the write may happen once a human says so
  allow — say nothing, let it through

The rules are the gate's rules, moved earlier. `cargo xtask verify-foundations`
catches a violation after it is committed; this catches it before it is written,
which is the difference between a gate and a habit.

**This hook may not reach outside the plugin.** A copied plugin has no path back
to the repository it was installed from, so the repo is located through
`CLAUDE_PROJECT_DIR`, which the harness sets. With no project directory there is
nothing to police and the hook stays silent.
"""
import json
import os
import sys

# Only the refusals live here. Both warnings — 500 lines of source, 30 lines of
# a CLAUDE.md — are the gate's, because a warning is something you read and a
# hook is something you answer, and a hook's `ask` overrides every permission
# mode by design. `xtask/src/rules.rs` carries all four numbers and the
# reasoning; the two files must not drift on the ones they share.
FAIL_LINES = 900
CLAUDE_MD_FAIL = 50

# Untyped JSON is allowed exactly where bytes enter the process — plus the
# gate itself, which names the pattern it forbids and so always matches itself.
# `xtask/src/rules.rs` carries the same exemption; the two must not drift.
JSON_ALLOWED = ("crates/store/", "crates/ipc/", "xtask/")


def answer(decision: str, reason: str) -> None:
    """Emit a PreToolUse decision and exit. `allow` is silent by convention."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": decision,
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    root = os.environ.get("CLAUDE_PROJECT_DIR")
    if not root:
        sys.exit(0)

    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not path:
        sys.exit(0)

    try:
        rel = os.path.relpath(path, root).replace("\\", "/")
    except ValueError:
        sys.exit(0)
    if rel.startswith(".."):
        sys.exit(0)  # outside the repo: not this gate's business

    # ---- rule: a generated file is not hand-edited -----------------------
    #
    # The gate already fails on a stale or hand-edited output, but that is
    # after the fact: a whole turn can go into editing a file whose next
    # regeneration throws the edit away, and the report arrives too late to
    # stop it. This refuses the write instead.
    #
    # There is deliberately no list of generated files here. Every generator
    # writes the same marker into its own output, so the hook asks the file
    # rather than asking a list that would have to be kept in step with the
    # generators — which is the drift this repo keeps removing.
    if os.path.exists(path):
        try:
            with open(path, encoding="utf-8", errors="ignore") as f:
                head = f.read(400)
        except OSError:
            head = ""
        if "GENERATED by `cargo xtask" in head:
            task = head.split("GENERATED by `", 1)[1].split("`", 1)[0]
            answer(
                "deny",
                f"{rel} is generated. Editing it here is thrown away by the next "
                f"run and fails the gate in between. Change what it is generated "
                f"from, then run `{task}`.",
            )
            return

    # ---- rule: every file under crates/*/src/ is in the manifest ----------
    parts = rel.split("/")
    under_crate_src = len(parts) > 3 and parts[0] == "crates" and parts[2] == "src"
    if under_crate_src:
        manifest = os.path.join(root, "foundations-manifest.txt")
        listed = set()
        try:
            with open(manifest) as f:
                listed = {line.strip() for line in f if line.strip()}
        except OSError:
            answer("deny", "foundations-manifest.txt is missing, so no write "
                           "under crates/*/src/ can be checked against it.")
        if rel not in listed:
            answer("deny", f"{rel} is not in foundations-manifest.txt. Add the "
                           "path to the manifest, sorted, in the same change "
                           "that adds the file — the manifest is how a file "
                           "nobody decided on becomes visible as a diff.")

    # ---- rule: no serde_json::from_* outside store and ipc ---------------
    #
    # Rust source only, matching the gate rule exactly. This checked every file
    # and the gate checked `.rs` under the source roots, so a contract that
    # described the ban was refused while the gate would have passed it — and
    # the document got reworded into something less precise to get past the
    # hook. A rule its own documentation cannot state is a rule that decays.
    written = tool_input.get("content") or tool_input.get("new_string") or ""
    rust_source = rel.endswith(".rs") and rel.split("/", 1)[0] in (
        "crates", "apps", "packages", "xtask",
    )
    if rust_source and "serde_json::from_" in written and not rel.startswith(JSON_ALLOWED):
        answer("deny", f"{rel} would contain `serde_json::from_*`. Untyped JSON "
                       "belongs to `store` and `ipc`, the two places bytes enter "
                       "the process; everywhere else a value arrives typed.")

    # ---- rule: a CLAUDE.md routes, it does not explain -------------------
    lines = projected_lines(root, rel, tool_input)
    if rel.endswith("CLAUDE.md") and lines is not None:
        if lines > CLAUDE_MD_FAIL:
            answer("deny", f"{rel} would be about {lines} lines, over "
                           f"{CLAUDE_MD_FAIL}. A CLAUDE.md routes; it does not "
                           "explain. Move the explanation to a practice doc, a "
                           "skill or Notion and leave the pointer. v1's agent "
                           "file reached 328 lines one reasonable paragraph at "
                           "a time.")

    # ---- rule: 500 warns and needs acknowledgment, 900 fails -------------
    #
    # Source only, matching `no_file_too_long` exactly. This applied to every
    # file, and the second-largest contract in the repository was compressed by
    # a quarter to get past it — a real loss, to satisfy a ceiling the gate
    # would never have applied to a markdown document.
    #
    # A hook stricter than the gate is worse than no hook: it is invisible in
    # CI, it fires at the moment somebody is mid-task, and what it produces is
    # a workaround rather than a fix. This is the second one found in a day.
    #
    # It also no longer asks, only refuses. A hook's `ask` overrides every
    # permission mode by design, so the warning at 500 stopped every write of a
    # large Rust file and no setting could quiet it — while a workspace was
    # being written from nothing. The gate still warns at 500, where a warning
    # is read rather than answered, and the hook keeps the refusal at 900 that
    # a gate run would only catch afterwards.
    # If a rule exists in both places, the scopes are part of the rule.
    if lines is not None and rel.endswith((".rs", ".ts", ".tsx")) and rel.split("/", 1)[0] in (
        "crates", "apps", "packages", "xtask",
    ):
        if lines > FAIL_LINES:
            answer("deny", f"{rel} would be about {lines} lines, over {FAIL_LINES}. "
                           "Split it.")

    sys.exit(0)


def projected_lines(root: str, rel: str, tool_input: dict) -> "int | None":
    """Line count the file would have after this write.

    Exact for `Write`, which carries the whole file. **Estimated for `Edit`**,
    from the delta between the strings being swapped — the hook runs before the
    edit, so the real result does not exist yet. The estimate is only ever used
    against a threshold, and being a line or two out at 500 does not change the
    answer.
    """
    content = tool_input.get("content")
    if content is not None:
        return len(content.splitlines())

    old, new = tool_input.get("old_string"), tool_input.get("new_string")
    if old is None or new is None:
        return None
    try:
        with open(os.path.join(root, rel)) as f:
            current = len(f.read().splitlines())
    except OSError:
        return None
    delta = len(new.splitlines()) - len(old.splitlines())
    if tool_input.get("replace_all"):
        return None  # occurrence count is unknown before the edit runs
    return current + delta


main()
