//! What the rule can be wrong about without anything looking wrong.
//!
//! The rule itself reads the repository, and the repository is in one state at
//! a time — the passing one. So the tests here are about the two judgements it
//! makes on the way: which lines count as a declaration, and which count as a
//! reading. Both have a failure mode that is silent in the same direction —
//! finding a reader that is not one, and passing.

use super::*;

/// The shape the generator writes, reduced to what `exports` asks of it.
const EMITTED: &str = "\
// GENERATED by `pnpm --filter @armada/desktop codegen`. Do not hand-edit.
import type { LucideIcon } from \"lucide-react\";

export type Rendering = {
  readonly verb: string | null;
};

export const JOB_STATUS: Readonly<Record<string, Rendering | undefined>> = {
  \"queued\": { verb: \"queued\" },
};

export const GAPS: readonly Gap[] = [
];
";

#[test]
fn every_exported_const_is_found_with_its_line() {
    let found = exports(EMITTED, "generated.ts");
    let named: Vec<(&str, usize)> = found
        .iter()
        .map(|one| (one.name.as_str(), one.line))
        .collect();
    assert_eq!(named, vec![("JOB_STATUS", 8), ("GAPS", 12)]);
}

/// The line that made `consts only` a decision rather than an oversight: a
/// generated module declares the shapes its maps are made of, and those are
/// read inside the file that declares them.
#[test]
fn an_exported_type_is_not_a_vocabulary() {
    assert!(!exports(EMITTED, "generated.ts")
        .iter()
        .any(|one| one.name == "Rendering"));
}

/// Every name one statement imports, so a test can read a source the way the
/// rule does.
fn named(source: &str) -> Vec<String> {
    let mut out = Vec::new();
    for (_, stmt) in statements(source) {
        let Some((open, close)) = stmt.find('{').zip(stmt.rfind('}')) else {
            continue;
        };
        for one in stmt[open + 1..close].split(',') {
            if let Some(word) = one.split_whitespace().next() {
                if word != "type" {
                    out.push(word.to_string());
                }
            }
        }
    }
    out
}

/// An import long enough to wrap is how a file reaching for four vocabularies
/// at once is written — `phases.tsx` reaches for four — and a line scan sees
/// four names it cannot attribute and a specifier carrying none.
#[test]
fn an_import_that_wraps_is_read_as_one_statement() {
    let source = "\
import {
  ADVANCE_GATE,
  CHECK_ADVANCES,
  CRITERION_VERDICT_CHECK,
  type Rendering,
} from \"@armada/components\";
";
    let found = statements(source);
    assert_eq!(found.len(), 1);
    assert_eq!(found[0].0, 1);
    assert_eq!(
        specifier(&found[0].1).as_deref(),
        Some("@armada/components")
    );
    assert_eq!(
        named(source),
        vec!["ADVANCE_GATE", "CHECK_ADVANCES", "CRITERION_VERDICT_CHECK"]
    );
}

/// The whole reason a reading is an import. Every instance of this defect
/// arrived with a comment naming the registry, and the word `import` inside one
/// is what made an earlier draft of this scan attribute a re-export to a
/// statement six lines above it.
#[test]
fn a_comment_naming_the_vocabulary_is_not_a_reader() {
    let source = "\
/**
 * `evidence_type` renders as the wire spells it. `enum-verbs.toml` carries no
 * rows for it, so EVIDENCE_TYPE is empty and an importer gets nothing.
 */
// import { EVIDENCE_TYPE } from \"@armada/components\"; — not yet
export * from \"./generated/vocabulary\";
const trail = (step) => step.evidence_type;
";
    assert!(named(source).is_empty());
}

/// `Composer.tsx` declares `const ORIGIN = \"manual\"`, which has nothing to do
/// with the `origin` vocabulary and would have counted as a reader under a word
/// search. Found by proving the rule fires, which is why the rule reads
/// imports.
#[test]
fn a_local_of_the_same_name_is_not_a_reading() {
    assert!(named("const ORIGIN = \"manual\";\nconst at = ORIGIN;\n").is_empty());
}

/// A specifier outside `@armada/` and `generated/` is somebody else's symbol,
/// whatever it is called.
#[test]
fn only_the_routes_a_generated_symbol_travels_are_read() {
    for (spec, ours) in [
        ("@armada/components", true),
        ("@armada/protocol", true),
        ("../../generated/vocabulary", true),
        ("./Composer", false),
        ("lucide-react", false),
    ] {
        let carries = spec.starts_with("@armada/") || spec.contains("generated");
        assert_eq!(carries, ours, "{spec}");
    }
}

/// The rule runs against the repository it is checked into. A green here says
/// every vocabulary Bridge generates today is drawn somewhere or declared.
#[test]
fn the_repository_reads_everything_it_generates() {
    let report = every_generated_vocabulary_has_a_reader(&crate::repo_root());
    let complaints: Vec<&String> = report
        .findings
        .iter()
        .map(|f| match f {
            crate::Finding::Fail(what) | crate::Finding::Warn(what) => what,
        })
        .collect();
    assert!(complaints.is_empty(), "{complaints:#?}");
}

/// The declaration list is checked in both directions, and this is the half
/// that keeps it honest: an entry that outlives its symbol reads as a decision
/// somebody made, when it is a line nobody deleted.
#[test]
fn the_declared_vocabularies_are_all_still_emitted() {
    for (name, why) in AHEAD_OF_ITS_SURFACE {
        assert!(
            !why.trim().is_empty(),
            "`{name}` is declared with no reason"
        );
        let emitted = GENERATED.iter().any(|file| {
            fs::read_to_string(crate::repo_root().join(file))
                .map(|text| exports(&text, file).iter().any(|one| &one.name == name))
                .unwrap_or(false)
        });
        assert!(
            emitted,
            "`{name}` is declared ahead of a surface and no generated module exports it"
        );
    }
}
