//! The rule's own negative tests.
//!
//! A rule that has never been shown to fail asserts nothing, and this one has
//! to fail on a pair the repository held for a day: a source bumped to 6.0 and
//! a constant left at 5.7. Each failure is proved against a pair written here
//! rather than against the repository, which can only be in one state at a
//! time — and is in the agreeing one.

use super::*;
use crate::Finding;

/// Every finding a report holds, as text.
fn findings(report: &Report) -> Vec<String> {
    report
        .findings
        .iter()
        .map(|f| match f {
            Finding::Fail(what) | Finding::Warn(what) => what.clone(),
        })
        .collect()
}

/// The source file, as the repository writes it: prose, then the two keys.
fn source(major: u32, minor: u32) -> String {
    format!(
        "# The version of the Fleet <-> Bridge IPC protocol.\n\nmajor = {major}\nminor = {minor}\n"
    )
}

/// The generated constant, as the codegen writes it.
fn mirror(major: u32, minor: u32) -> String {
    format!(
        "// GENERATED by `{CODEGEN}`. Do not hand-edit.\n//\n// `{SOURCE}` is what both sides \
         read.\n\nexport const PROTOCOL_VERSION = {{ major: {major}, minor: {minor} }};\n"
    )
}

/// Every finding the rule produces for one pair.
fn run(source: &str, mirror: &str) -> Vec<String> {
    let mut report = Report::new("test");
    check(source, mirror, &mut report);
    findings(&report)
}

/// The one finding a pair produces, or a panic naming what it produced instead.
fn only(found: Vec<String>) -> String {
    assert_eq!(found.len(), 1, "{found:?}");
    found.into_iter().next().unwrap_or_default()
}

#[test]
fn a_source_and_a_constant_that_agree_report_nothing() {
    assert_eq!(run(&source(6, 0), &mirror(6, 0)), Vec::<String>::new());
}

#[test]
fn a_major_that_moved_and_a_constant_that_did_not_is_refused() {
    let found = only(run(&source(6, 0), &mirror(5, 7)));
    assert!(found.contains(SOURCE), "{found}");
    assert!(found.contains(MIRROR), "{found}");
    assert!(found.contains("6.0"), "{found}");
    assert!(found.contains("5.7"), "{found}");
}

#[test]
fn a_minor_that_moved_and_a_constant_that_did_not_is_refused() {
    let found = only(run(&source(5, 8), &mirror(5, 7)));
    assert!(found.contains("5.8") && found.contains("5.7"), "{found}");
}

#[test]
fn a_constant_ahead_of_the_source_is_refused_the_same_way() {
    let found = only(run(&source(5, 7), &mirror(6, 0)));
    assert!(found.contains("5.7") && found.contains("6.0"), "{found}");
}

#[test]
fn the_refusal_names_the_command_that_writes_the_file() {
    let found = only(run(&source(6, 0), &mirror(5, 7)));
    assert!(found.contains(CODEGEN), "{found}");
}

#[test]
fn a_source_with_no_major_is_refused_and_so_is_one_with_no_minor() {
    let no_major = run("minor = 0\n", &mirror(6, 0));
    assert!(
        no_major.iter().any(|f| f.contains("no `major = <n>` line")),
        "{no_major:?}"
    );

    let no_minor = run("major = 6\n", &mirror(6, 0));
    assert!(
        no_minor.iter().any(|f| f.contains("no `minor = <n>` line")),
        "{no_minor:?}"
    );
}

#[test]
fn a_source_number_that_is_not_a_number_is_refused() {
    let found = run("major = six\nminor = 0\n", &mirror(6, 0));
    assert!(
        found.iter().any(|f| f.contains("is not a number")),
        "{found:?}"
    );
}

#[test]
fn a_source_key_the_file_does_not_define_is_refused() {
    let found = run("major = 6\nminor = 0\npatch = 1\n", &mirror(6, 0));
    assert_eq!(
        only(found),
        format!("{SOURCE}:3 — `patch` is not a key this file defines: major, minor")
    );
}

#[test]
fn a_source_key_set_twice_is_refused() {
    let found = only(run("major = 6\nminor = 0\nmajor = 6\n", &mirror(6, 0)));
    assert!(found.contains("already set at line 1"), "{found}");
}

#[test]
fn a_source_line_that_is_neither_a_comment_nor_a_pair_is_refused() {
    let found = only(run("[protocol]\nmajor = 6\nminor = 0\n", &mirror(6, 0)));
    assert!(
        found.contains("neither a comment nor `key = value`"),
        "{found}"
    );
}

#[test]
fn a_commented_out_number_in_the_source_is_not_the_version() {
    let text = "# it was `major = 99` once\nmajor = 6\nminor = 0\n";
    assert_eq!(run(text, &mirror(6, 0)), Vec::<String>::new());
}

#[test]
fn a_comment_after_the_value_is_not_part_of_the_number() {
    let text = "major = 6  # bumped by #270\nminor = 0\n";
    assert_eq!(run(text, &mirror(6, 0)), Vec::<String>::new());
}

#[test]
fn a_constant_that_is_a_bare_number_is_refused() {
    let bare = "// GENERATED\nexport const PROTOCOL_VERSION = 6;\n";
    let found = run(&source(6, 0), bare);
    assert_eq!(found.len(), 2, "{found:?}");
    assert!(found[0].contains("names no `major`"), "{found:?}");
    assert!(found[1].contains("names no `minor`"), "{found:?}");
    assert!(found[0].contains("a bare number"), "{found:?}");
}

#[test]
fn a_constant_with_no_minor_is_refused() {
    let half = "// GENERATED\nexport const PROTOCOL_VERSION = { major: 6 };\n";
    let found = only(run(&source(6, 0), half));
    assert!(found.contains("names no `minor`"), "{found}");
}

#[test]
fn a_file_exporting_no_constant_is_refused() {
    let empty = "// GENERATED by the codegen. Do not hand-edit.\n";
    let found = only(run(&source(6, 0), empty));
    assert!(found.contains("exports no `PROTOCOL_VERSION`"), "{found}");
    assert!(found.contains(CODEGEN), "{found}");
}

#[test]
fn prose_above_the_constant_is_not_read_as_the_constant() {
    let text = "// GENERATED\n// It was `{ major: 5, minor: 7 }` before #270.\n\
                export const PROTOCOL_VERSION = { major: 6, minor: 0 };\n";
    assert_eq!(run(&source(6, 0), text), Vec::<String>::new());
}

#[test]
fn spacing_in_the_constant_does_not_change_what_is_read() {
    let compact = "// GENERATED\nexport const PROTOCOL_VERSION={major:6,minor:0};\n";
    assert_eq!(run(&source(6, 0), compact), Vec::<String>::new());
}

#[test]
fn a_constant_that_does_not_say_it_is_generated_is_refused() {
    let hand = "export const PROTOCOL_VERSION = { major: 6, minor: 0 };\n";
    let found = only(run(&source(6, 0), hand));
    assert!(found.contains("does not say it is generated"), "{found}");
}

#[test]
fn two_empty_files_name_both_of_them() {
    let found = run("", "");
    assert!(found.iter().any(|f| f.starts_with(SOURCE)), "{found:?}");
    assert!(found.iter().any(|f| f.starts_with(MIRROR)), "{found:?}");
}
