// GENERATED by `cargo xtask verify-tokens --write`. Do not hand-edit.
//
// Tailwind's default scales are REPLACED, not extended. `theme.extend`
// leaves `bg-slate-800`, `h-16` and Tailwind's own `text-lg` reachable, and
// each of those is an off-contract value that compiles clean.
//
// Every value is `var(--token)`, so the CSS custom property remains the one
// place a value lives at runtime and a theme change cannot fork from it.
//
// Deliberately not utilities:
//   --window-floor — the window's hard floor, read by main
//   --layout-breakpoint — a media query bound, not a utility
//   --focus-ring — an outline shorthand, not a scale value
//   --focus-ring-offset — paired with --focus-ring
//   --row-focus-bar — a border shorthand, not a scale value

export default {
  colors: {
    accent: {
      DEFAULT: 'var(--accent)',
      hover: 'var(--accent-hover)',
      muted: 'var(--accent-muted)',
    },
    bg: {
      base: 'var(--bg-base)',
      hover: 'var(--bg-hover)',
      overlay: 'var(--bg-overlay)',
      raised: 'var(--bg-raised)',
      sunken: 'var(--bg-sunken)',
    },
    diff: {
      'add-bg': 'var(--diff-add-bg)',
      'add-fg': 'var(--diff-add-fg)',
      context: 'var(--diff-context)',
      'del-bg': 'var(--diff-del-bg)',
      'del-fg': 'var(--diff-del-fg)',
    },
    fg: {
      default: 'var(--fg-default)',
      inverse: 'var(--fg-inverse)',
      muted: 'var(--fg-muted)',
      subtle: 'var(--fg-subtle)',
    },
    status: {
      'awaiting-approval': 'var(--status-awaiting-approval)',
      'awaiting-approval-bg': 'var(--status-awaiting-approval-bg)',
      'awaiting-attestation': 'var(--status-awaiting-attestation)',
      'awaiting-attestation-bg': 'var(--status-awaiting-attestation-bg)',
      'awaiting-review': 'var(--status-awaiting-review)',
      'awaiting-review-bg': 'var(--status-awaiting-review-bg)',
      'completed-failed': 'var(--status-completed-failed)',
      'completed-failed-bg': 'var(--status-completed-failed-bg)',
      'completed-success': 'var(--status-completed-success)',
      'completed-success-bg': 'var(--status-completed-success-bg)',
      escalated: 'var(--status-escalated)',
      'escalated-bg': 'var(--status-escalated-bg)',
      killed: 'var(--status-killed)',
      'killed-bg': 'var(--status-killed-bg)',
      'not-started': 'var(--status-not-started)',
      'not-started-bg': 'var(--status-not-started-bg)',
      piloted: 'var(--status-piloted)',
      'piloted-bg': 'var(--status-piloted-bg)',
      rejected: 'var(--status-rejected)',
      'rejected-bg': 'var(--status-rejected-bg)',
      running: 'var(--status-running)',
      'running-bg': 'var(--status-running-bg)',
      superseded: 'var(--status-superseded)',
      'superseded-bg': 'var(--status-superseded-bg)',
    },
    step: {
      advanced: 'var(--step-advanced)',
      failed: 'var(--step-failed)',
      'failed-bg': 'var(--step-failed-bg)',
      running: 'var(--step-running)',
      'stopped-bg': 'var(--step-stopped-bg)',
      waiting: 'var(--step-waiting)',
    },
    surface: {
      canvas: 'var(--surface-canvas)',
      card: 'var(--surface-card)',
      floating: 'var(--surface-floating)',
      row: 'var(--surface-row)',
      'row-hover': 'var(--surface-row-hover)',
      'row-selected': 'var(--surface-row-selected)',
      well: 'var(--surface-well)',
    },
    text: {
      body: 'var(--text-body)',
      label: 'var(--text-label)',
      meta: 'var(--text-meta)',
      'on-accent': 'var(--text-on-accent)',
    },
    verdict: {
      met: 'var(--verdict-met)',
      'not-met': 'var(--verdict-not-met)',
    },
  },
  borderColor: {
    card: 'var(--edge-card)',
    default: 'var(--border-default)',
    focus: 'var(--edge-focus)',
    rule: 'var(--edge-rule)',
    strong: 'var(--border-strong)',
    subtle: 'var(--border-subtle)',
  },
  borderRadius: {
    lg: 'var(--radius-lg)',
    md: 'var(--radius-md)',
    sm: 'var(--radius-sm)',
  },
  boxShadow: {
    overlay: 'var(--shadow-overlay)',
  },
  fontFamily: {
    mono: 'var(--font-mono)',
    sans: 'var(--font-sans)',
  },
  fontSize: {
    '2xl': ['var(--text-2xl)', 'var(--leading-2xl)'],
    '2xs': ['var(--text-2xs)', 'var(--leading-2xs)'],
    base: ['var(--text-base)', 'var(--leading-base)'],
    lg: ['var(--text-lg)', 'var(--leading-lg)'],
    sm: ['var(--text-sm)', 'var(--leading-sm)'],
    xl: ['var(--text-xl)', 'var(--leading-xl)'],
    xs: ['var(--text-xs)', 'var(--leading-xs)'],
  },
  fontWeight: {
    body: 'var(--weight-body)',
    heading: 'var(--weight-heading)',
    medium: 'var(--weight-medium)',
  },
  height: {
    badge: 'var(--h-badge)',
    control: 'var(--h-control)',
    'control-sm': 'var(--h-control-sm)',
    kbd: 'var(--h-kbd)',
    'menu-item': 'var(--h-menu-item)',
    row: 'var(--h-row)',
    'row-header': 'var(--h-row-header)',
    'status-bar': 'var(--h-status-bar)',
  },
  letterSpacing: {
    caps: 'var(--tracking-caps)',
  },
  maxHeight: {
    palette: 'var(--palette-max-height)',
  },
  maxWidth: {
    palette: 'var(--palette-width)',
    sidebar: 'var(--sidebar-max)',
  },
  minHeight: {
    'row-stacked': 'var(--h-row-stacked)',
  },
  minWidth: {
    sidebar: 'var(--sidebar-min)',
  },
  padding: {
    card: 'var(--pad-card)',
    'row-stacked': 'var(--pad-row-stacked)',
  },
  spacing: {
    '1': 'var(--space-1)',
    '12': 'var(--space-12)',
    '2': 'var(--space-2)',
    '3': 'var(--space-3)',
    '4': 'var(--space-4)',
    '6': 'var(--space-6)',
    '8': 'var(--space-8)',
    rail: 'var(--sidebar-rail)',
    section: 'var(--gap-section)',
    sidebar: 'var(--sidebar-default)',
  },
  transitionDelay: {
    tooltip: 'var(--tooltip-delay)',
  },
  transitionDuration: {
    base: 'var(--duration-base)',
    fast: 'var(--duration-fast)',
    pulse: 'var(--duration-pulse)',
  },
  transitionTimingFunction: {
    DEFAULT: 'var(--ease)',
  },
}
