//! The three generated files, and the one table that decides where a token
//! lands in the Tailwind theme.
//!
//! Split from `tokens.rs` because the audiences differ: that file is the
//! reader — how a `.css` file becomes a list of tokens — and this one is what
//! somebody edits when a token needs a home.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::tokens::{Slot, Token, THEME};

/// The first entry in [`THEME`] a name matches. Exact entries are listed
/// before prefixes, so an exact name wins.
fn slot(name: &str) -> Option<&'static Slot> {
    THEME
        .iter()
        .find(|(pat, _)| if pat.ends_with('-') { name.starts_with(pat) } else { name == *pat })
        .map(|(_, s)| s)
}

/// `packages/tokens/tokens.css` — the cascade, verbatim, in one file.
pub fn tokens_css(root: &Path, sources: &[String]) -> String {
    let mut out = String::from(
        "/* GENERATED by `cargo xtask verify-tokens --write`. Do not hand-edit.\n\
         \x20  Authored in packages/tokens/src/, concatenated here in the order\n\
         \x20  styles.css declares. base.css is not in this file: it consumes\n\
         \x20  tokens rather than declaring them, and belongs to the renderer. */\n",
    );
    for name in sources {
        let text = fs::read_to_string(root.join("packages/tokens/src").join(name))
            .unwrap_or_default();
        let _ = write!(out, "\n/* ── {name} ─────────────────────────────── */\n{text}");
        if !text.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

/// `packages/tokens/tokens.json` — every token, its source and its reasoning.
/// Read by the primitive spec test at M1 step 5.5.
pub fn tokens_json(tokens: &[Token]) -> String {
    let mut out = String::from("{\n  \"tokens\": [\n");
    for (i, t) in tokens.iter().enumerate() {
        let comma = if i + 1 == tokens.len() { "" } else { "," };
        let _ = write!(out, "    {{\n      \"name\": \"{}\",\n", t.name);
        let _ = write!(out, "      \"value\": {},\n", json_str(&t.value));
        let _ = write!(out, "      \"file\": \"{}\",\n", t.file);
        match &t.alias_of {
            Some(a) => {
                let _ = write!(out, "      \"aliasOf\": \"{a}\",\n");
            }
            None => {
                let _ = write!(out, "      \"aliasOf\": null,\n");
            }
        }
        match &t.note {
            Some(n) => {
                let _ = write!(out, "      \"note\": {}\n", json_str(n));
            }
            None => {
                let _ = write!(out, "      \"note\": null\n");
            }
        }
        let _ = write!(out, "    }}{comma}\n");
    }
    out.push_str("  ]\n}\n");
    out
}

fn json_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `packages/tokens/tailwind.theme.js` — the theme keys, named after the
/// tokens. Every value is `var(--token)` rather than a literal, so the CSS
/// custom property stays the one thing that holds a value at runtime.
pub fn tailwind_theme(tokens: &[Token]) -> Result<String, String> {
    let leadings: BTreeMap<&str, &str> = tokens
        .iter()
        .filter_map(|t| t.name.strip_prefix("--leading-").map(|k| (k, t.name.as_str())))
        .collect();

    // group -> key -> value expression
    let mut groups: BTreeMap<&'static str, BTreeMap<String, String>> = BTreeMap::new();
    let mut css_only: Vec<(&str, &'static str)> = Vec::new();

    for t in tokens {
        let Some(slot) = slot(&t.name) else {
            return Err(format!(
                "{} is declared in {} and classified nowhere — add it to THEME in \
                 xtask/src/tokens.rs, or say why it is CSS-only",
                t.name, t.file
            ));
        };
        match slot {
            Slot::CssOnly(why) => css_only.push((&t.name, why)),
            Slot::Leading => {}
            Slot::FontSize => {
                let key = t.name.trim_start_matches("--text-");
                let Some(leading) = leadings.get(key) else {
                    return Err(format!(
                        "{} has no --leading-{key} — a font size is a size and a line \
                         height together, or it is a colour that wants an exact entry \
                         in THEME",
                        t.name
                    ));
                };
                groups.entry("fontSize").or_default().insert(
                    key.to_string(),
                    format!("['var({})', 'var({leading})']", t.name),
                );
            }
            Slot::Named(path, key) => {
                groups
                    .entry(path)
                    .or_default()
                    .insert((*key).to_string(), format!("'var({})'", t.name));
            }
            Slot::Group(path) => {
                let key = theme_key(&t.name);
                groups
                    .entry(path)
                    .or_default()
                    .insert(key, format!("'var({})'", t.name));
            }
        }
    }

    let mut out = String::from(
        "// GENERATED by `cargo xtask verify-tokens --write`. Do not hand-edit.\n\
         //\n\
         // Tailwind's default scales are REPLACED, not extended. `theme.extend`\n\
         // leaves `bg-slate-800`, `h-16` and Tailwind's own `text-lg` reachable, and\n\
         // each of those is an off-contract value that compiles clean.\n\
         //\n\
         // Every value is `var(--token)`, so the CSS custom property remains the one\n\
         // place a value lives at runtime and a theme change cannot fork from it.\n",
    );
    if !css_only.is_empty() {
        out.push_str("//\n// Deliberately not utilities:\n");
        for (name, why) in &css_only {
            let _ = writeln!(out, "//   {name} — {why}");
        }
    }
    out.push_str("\nexport default {\n");

    // Nested paths ("colors.bg") are grouped under their first segment.
    let mut nested: BTreeMap<&str, BTreeMap<&str, &BTreeMap<String, String>>> = BTreeMap::new();
    let mut flat: BTreeMap<&str, &BTreeMap<String, String>> = BTreeMap::new();
    for (path, entries) in &groups {
        match path.split_once('.') {
            Some((outer, inner)) => {
                nested.entry(outer).or_default().insert(inner, entries);
            }
            None => {
                flat.insert(path, entries);
            }
        }
    }
    for (outer, inners) in &nested {
        let _ = writeln!(out, "  {outer}: {{");
        for (inner, entries) in inners {
            let _ = writeln!(out, "    {inner}: {{");
            for (k, v) in *entries {
                let _ = writeln!(out, "      {}: {v},", quote_key(k));
            }
            out.push_str("    },\n");
        }
        out.push_str("  },\n");
    }
    for (path, entries) in &flat {
        let _ = writeln!(out, "  {path}: {{");
        for (k, v) in *entries {
            let _ = writeln!(out, "    {}: {v},", quote_key(k));
        }
        out.push_str("  },\n");
    }
    out.push_str("}\n");
    Ok(out)
}

/// The class-name half of a token name: `--status-running` under
/// `colors.status` is `running`. A token that is only its group — `--accent` —
/// becomes `DEFAULT`, which is how Tailwind spells the bare class.
fn theme_key(name: &str) -> String {
    let stripped = name.trim_start_matches("--");
    for (pat, _) in THEME {
        let Some(prefix) = pat.strip_prefix("--") else { continue };
        if !prefix.ends_with('-') {
            continue;
        }
        if let Some(rest) = stripped.strip_prefix(prefix) {
            return rest.to_string();
        }
    }
    if stripped.contains('-') { stripped.to_string() } else { "DEFAULT".to_string() }
}

fn quote_key(k: &str) -> String {
    if k.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') && !k.starts_with(|c: char| c.is_ascii_digit()) {
        k.to_string()
    } else {
        format!("'{k}'")
    }
}
