//! The three generated files, and the one table that decides where a token
//! lands in the Tailwind theme.
//!
//! Split from `tokens.rs` because the audiences differ: that file is the
//! reader — how a `.css` file becomes a list of tokens — and this one is what
//! somebody edits when a token needs a home.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::tokens::{Slot, Token, THEME};

/// The first entry in [`THEME`] a name matches. Exact entries are listed
/// before prefixes, so an exact name wins.
fn slot(name: &str) -> Option<&'static Slot> {
    THEME
        .iter()
        .find(|(pat, _)| if pat.ends_with('-') { name.starts_with(pat) } else { name == *pat })
        .map(|(_, s)| s)
}

/// `packages/tokens/tokens.css` — the cascade, verbatim, in one file.
pub fn tokens_css(root: &Path, sources: &[String]) -> String {
    let mut out = String::from(
        "/* GENERATED by `cargo xtask verify-tokens --write`. Do not hand-edit.\n\
         \x20  Authored in packages/tokens/src/, concatenated here in the order\n\
         \x20  styles.css declares. base.css is not in this file: it consumes\n\
         \x20  tokens rather than declaring them, and belongs to the renderer. */\n",
    );
    for name in sources {
        let text = fs::read_to_string(root.join("packages/tokens/src").join(name))
            .unwrap_or_default();
        let _ = write!(out, "\n/* ── {name} ─────────────────────────────── */\n{text}");
        if !text.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

/// `packages/tokens/tokens.json` — every token, its source and its reasoning.
/// Read by the primitive spec test at M1 step 5.5.
pub fn tokens_json(tokens: &[Token]) -> String {
    let mut out = String::from("{\n  \"tokens\": [\n");
    for (i, t) in tokens.iter().enumerate() {
        let comma = if i + 1 == tokens.len() { "" } else { "," };
        let _ = write!(out, "    {{\n      \"name\": \"{}\",\n", t.name);
        let _ = write!(out, "      \"value\": {},\n", json_str(&t.value));
        let _ = write!(out, "      \"file\": \"{}\",\n", t.file);
        match &t.alias_of {
            Some(a) => {
                let _ = write!(out, "      \"aliasOf\": \"{a}\",\n");
            }
            None => {
                let _ = write!(out, "      \"aliasOf\": null,\n");
            }
        }
        match &t.note {
            Some(n) => {
                let _ = write!(out, "      \"note\": {}\n", json_str(n));
            }
            None => {
                let _ = write!(out, "      \"note\": null\n");
            }
        }
        let _ = write!(out, "    }}{comma}\n");
    }
    out.push_str("  ]\n}\n");
    out
}

fn json_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `packages/tokens/tokens.theme.css` — the Tailwind v4 theme.
///
/// **`@theme inline`, not `@theme`.** The difference is where the value
/// resolves. Under plain `@theme` the emitted utility reads
/// `var(--color-bg-base)`, which is substituted once at `:root`, so a
/// `[data-theme="light"]` block redefining `--bg-base` never reaches it and a
/// theme variant needs a rebuild. Under `inline` the utility reads
/// `var(--bg-base)` and resolves at the element, so a variant is one CSS block.
/// Measured against 4.3.3, not assumed.
///
/// Every namespace is reset with `--<ns>-*: initial` first. Without that,
/// `bg-slate-800`, `h-16` and Tailwind's own `text-lg` stay reachable, and each
/// is an off-contract value that compiles clean.
pub fn theme_css(tokens: &[Token]) -> Result<String, String> {
    // ns -> key -> (variable, token it aliases)
    let mut entries: Vec<(String, String)> = Vec::new();
    let mut seen: BTreeMap<String, String> = BTreeMap::new();
    let mut namespaces: Vec<&str> = Vec::new();
    let mut leadings: Vec<(String, String)> = Vec::new();
    let mut css_only: Vec<(&str, &'static str)> = Vec::new();
    let mut literals: Vec<(String, String)> = Vec::new();

    for t in tokens {
        let Some(slot) = slot(&t.name) else {
            return Err(format!(
                "{} is declared in {} and classified nowhere — add it to THEME in \
                 xtask/src/tokens.rs, or say why it is CSS-only",
                t.name, t.file
            ));
        };
        let (ns, var) = match slot {
            Slot::CssOnly(why) => {
                css_only.push((&t.name, why));
                continue;
            }
            Slot::Leading => {
                let size = t.name.trim_start_matches("--leading-");
                leadings.push((format!("--text-{size}--line-height"), t.name.clone()));
                continue;
            }

            Slot::Literal => {
                literals.push((t.name.clone(), t.value.clone()));
                continue;
            }
            Slot::Named(ns, key) => (*ns, format!("--{ns}-{key}")),
            Slot::Ns(ns) => (*ns, format!("--{ns}-{}", key_for(&t.name))),
            Slot::NsFull(ns) => (*ns, format!("--{ns}-{}", t.name.trim_start_matches("--"))),
        };
        if let Some(other) = seen.insert(var.clone(), t.name.clone()) {
            return Err(format!(
                "{} and {other} both become `{var}` — one would silently overwrite the \
                 other. Give one an exact Named entry in THEME",
                t.name
            ));
        }
        if !ns.is_empty() && !namespaces.contains(&ns) {
            namespaces.push(ns);
        }
        entries.push((var, t.name.clone()));
    }

    let mut out = String::from(
        "/* GENERATED by `cargo xtask verify-tokens --write`. Do not hand-edit.\n\
         \x20\n\
         \x20  The Tailwind v4 theme. Import it after tokens.css, which declares the\n\
         \x20  --token variables every line below points at.\n\
         \x20\n\
         \x20  `inline` is load-bearing: it makes each utility read var(--token)\n\
         \x20  directly, so a theme variant is a CSS block redefining the token and\n\
         \x20  not a rebuild. Plain @theme freezes the value at :root.\n\
         \x20\n\
         \x20  Each namespace is reset to `initial` so Tailwind's own scales stop\n\
         \x20  resolving: bg-slate-800, h-16 and text-lg are off-contract values that\n\
         \x20  would otherwise compile clean. */\n\n\
         @theme inline {\n",
    );
    namespaces.sort_unstable();
    for ns in &namespaces {
        let _ = writeln!(out, "  --{ns}-*: initial;");
    }
    out.push('\n');
    if !literals.is_empty() {
        out.push_str(
            "  /* Already v4 theme variables, so they carry their value rather than
             \x20    aliasing themselves — `--text-sm: var(--text-sm)` is circular and
             \x20    would unset the variable. */\n",
        );
        for (name, value) in &literals {
            let _ = writeln!(out, "  {name}: {value};");
        }
        out.push('\n');
    }
    for (var, token) in &entries {
        let _ = writeln!(out, "  {var}: var({token});");
    }
    if !leadings.is_empty() {
        out.push_str("\n  /* Line heights, paired to their size. Not utilities of their own. */\n");
        for (var, token) in &leadings {
            let _ = writeln!(out, "  {var}: var({token});");
        }
    }
    out.push_str("}\n");
    if !css_only.is_empty() {
        out.push_str("\n/* Read from CSS as var(--token). No namespace carries them:\n");
        for (name, why) in &css_only {
            let _ = writeln!(out, "   {name} — {why}");
        }
        out.push_str("*/\n");
    }
    Ok(out)
}

/// The key half of a theme variable: `--status-running` under `color` becomes
/// `status-running`, `--h-row` under `spacing` becomes `row`. A token that is
/// only its prefix keeps its whole name.
fn key_for(name: &str) -> String {
    let stripped = name.trim_start_matches("--");
    for (pat, _) in THEME {
        let Some(prefix) = pat.strip_prefix("--") else { continue };
        if !prefix.ends_with('-') {
            continue;
        }
        if let Some(rest) = stripped.strip_prefix(prefix) {
            if !rest.is_empty() {
                return rest.to_string();
            }
        }
    }
    stripped.to_string()
}

