import { defineConfig } from 'electron-vite'
import tailwindcss from '@tailwindcss/vite'

// Three builds from one config: the main process, the preload bridge, and the
// renderer. The preload is the only thing that crosses between them, which is
// why it is a build of its own rather than an import.
export default defineConfig({
  main: { build: { lib: { entry: 'src/main/index.ts' } } },
  preload: { build: { lib: { entry: 'src/preload/index.ts' } } },
  // Tailwind v4 has no JS config: the theme is packages/tokens/tokens.theme.css,
  // generated by `cargo xtask verify-tokens` and imported by the renderer's
  // stylesheet. There is deliberately no tailwind.config.js to drift from it.
  renderer: { root: 'src/renderer', plugins: [tailwindcss()] },
})
