import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// Three builds from one config: the main process, the preload bridge, and the
// renderer. The preload is the only thing that crosses between them, which is
// why it is a build of its own rather than an import.
export default defineConfig({
  // Dependencies stay external in the main bundle: `ws` reaches for node
  // builtins and optional native helpers, and bundling it would inline
  // decisions its own package makes at require time. The token set is the
  // exception — it is data this build reads, and inlining it means no runtime
  // resolution of a JSON file through a workspace symlink.
  main: {
    build: { lib: { entry: 'src/main/index.ts' } },
    plugins: [externalizeDepsPlugin({ exclude: ['@armada/tokens'] })],
  },
  preload: { build: { lib: { entry: 'src/preload/index.ts' } } },
  // Tailwind v4 has no JS config: the theme is packages/tokens/tokens.theme.css,
  // generated by `cargo xtask verify-tokens` and imported by the renderer's
  // stylesheet. There is deliberately no tailwind.config.js to drift from it.
  renderer: { root: 'src/renderer', plugins: [react(), tailwindcss()] },
})
