//! The wire vocabulary, as DTOs rather than domain types.
//!
//! `From<core_model::Job> for ipc::JobSummary` at the Fleet boundary is where
//! redaction becomes an explicit, visible step. **A domain type on the wire is a
//! redaction decision nobody made.**
//!
//! `PROTOCOL_VERSION` is emitted by `build.rs` from `protocol-version.toml` at
//! the repo root, and a codegen step emits matching TypeScript from this crate's
//! types. Both generated outputs are checked in, so a cross-language breaking
//! change is a build failure rather than a runtime surprise.
//!
//! One of two crates permitted to deserialize, because this is where bytes
//! arrive from outside.

// `PROTOCOL_VERSION`, generated by build.rs from `protocol-version.toml`.
//
// Fleet outlives Bridge, so a mismatch happens mid-Job with Drones burning
// tokens rather than at a convenient startup. A peer that sees a version it
// does not know refuses rather than guessing.
include!(concat!(env!("OUT_DIR"), "/protocol_version.rs"));
